apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "mobilenet-server"
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    scaleTarget: 1
    #scaleMetric: concurrency
    containerConcurrency: 15
    # model:
    #   modelFormat:
    #     name: pytorch
    #   runtime: custom
    containers:
      - name: mobilenet
        image: leslie233/mobilenet:fast-test
        ports:
          - containerPort: 8080
        # resources:
        #   requests:
        #     cpu: 2
        #     memory: 5Gi
        #   limits:
        #     cpu: 10
        #     memory: 8Gi
        
        volumeMounts:
          - name: "model-volume"
            mountPath: "/models/"
    #     # Optional: you can specify environment variables if needed
    #     #env:
    #       # - name: MODEL_NAME
    #       #   value: "my-model"
    #     # Optional: set ports if your container uses non-default ports
    #     # ports:
    #     #   - containerPort: 8080
    # volumes:
    #   - name: "model-volume"
    #     hostPath:
    #       path: "/models/"
    volumes:
      - name: "model-volume"
        persistentVolumeClaim:
          claimName: models-pvc
