apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "shufflenet-server"
spec:
  predictor:
    minReplicas: 1      # Optional: minimum replicas
    maxReplicas: 2      # Maximum replicas
    scaleTarget: 1
    scaleMetric: concurrency
    # model:
    #   modelFormat:
    #     name: pytorch
    #   runtime: custom
    containers:
      - name: shufflenet
        image: leslie233/shufflenet:fast-test
        ports:
          - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 1Gi
        
        volumeMounts:
          - name: "model-volume"
            mountPath: "/models/"
    #     # Optional: you can specify environment variables if needed
    #     #env:
    #       # - name: MODEL_NAME
    #       #   value: "my-model"
    #     # Optional: set ports if your container uses non-default ports
    #     # ports:
    #     #   - containerPort: 8080
    # volumes:
    #   - name: "model-volume"
    #     hostPath:
    #       path: "/models/"
    volumes:
      - name: "model-volume"
        persistentVolumeClaim:
          claimName: models-pvc
