apiVersion: caps.in.tum.fastgshare/v1
kind: FaSTFunc
metadata:
  labels:
    app.kubernetes.io/name: fastfunc
    app.kubernetes.io/instance: fastfunc-sample
    app.kubernetes.io/part-of: scheduler
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: scheduler
    fast_function: resnet-fastpod
  annotations:
    fastgshare/gpu_quota_request: "0.5"
    fastgshare/gpu_quota_limit: "0.5"
    fastgshare/gpu_sm_partition: "30"
    fastgshare/gpu_mem: "2700000000"
    has-gpu/batch_size: "1"
  name: resnet50
  namespace: fast-gshare-fn
spec:
  selector:
    matchLabels:
      #fast_function: has-func-resnet50

  podSpec:
    containers:
    - name: resnet50
      image: docker.io/leslie233/resnet:fast-test
      ports:
        - containerPort: 8080
      readinessProbe:
        tcpSocket:
          port: 5000
        initialDelaySeconds: 3
        periodSeconds: 1
      # env:
      #   - name: CUDA_MPS_ACTIVE_THREAD_PERCENTAGE
      #     value: "60"
      # ports:
      # - containerPort: 5000
      #   hostPort: 5000
      volumeMounts:
        - name: "model-volume"
          mountPath: "/models/"
      # command: ["/bin/bash", "-c"]
      # args: ["sleep 7200"]
    volumes:
        - name: "model-volume"
          hostPath:
            path: "/models/"